trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo K8S Project!
- task: DownloadSecureFile@1
  name: pubkey
  inputs:
    secureFile: 'azure_rsa_key.pub'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(pubkey.secure,FilePath)'
    backendServiceArm: 'Devops-AyushTeke'
    backendAzureRmResourceGroupName: 'AyushTeke'
    backendAzureRmStorageAccountName: 'ayushtekedevops'
    backendAzureRmContainerName: 'ayush'
    backendAzureRmKey: 'ayush1504'
  displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
